### ISSUE TITLE
[Documentaion] Docker and Docker-Compose

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [documize/community#311]
It would be great if Documize had Docker Documentation so we could Dockerize our Documize.

**Comment by macnibblet** [comment]
I just started looking at this project too, and wanted to give it a test spin but didn't find a docker/docker-compose container to test against which is a pitty.

**Comment by HarveyKandola** [comment]
We'll prepare that this week and push up the Docker compose file for Dockerized setup

**Comment by HarveyKandola** [comment]
Try out the docker-compose file to see if it meets with your needs.

**Comment by Th3Whit3Wolf** [comment]
It works great. For clarity for other people I think the documentation might have more examples, like if someone is using an external database. Here's mine, though I am using a dockerfile I built. 

```yml
version: "3"

networks:
  web:
    external: true

services:
  documize:
    container_name: documize
    image: me/documize:3.2.0
    environment:
      DOCUMIZEPORT: 5001
      DOCUMIZEDB: host=db-name.ondigitalocean.com port=25000 dbname=documize user=documize password=P@SSw0rd sslmode=require
      DOCUMIZEDBTYPE: postgresql
      DOCUMIZESALT: hsk3Acndky8cdTNx3
      DOCUMIZELOCATION: selfhost
    restart: always
    networks:
      - web
    ports:
    - "5001:5001" 
```

**Comment by Th3Whit3Wolf** [comment]
Also has your team considered making an official image? It would be very simple to setup since you already have a dockerfile in your repo.

**Comment by HarveyKandola** [comment]
@Th3Whit3Wolf thanks for your example -- should help others.

We can provide Docker image with just the executable to make things easier for those who want to use image with Docker Compose.

Part of the (historic) reason for not doing so is because Documize just ships as a single binary executable.

**Comment by Th3Whit3Wolf** [comment]
I think it should also be noted that you could do 
```yaml
version: "3"

networks:
  web:
    external: true

services:
  documize:
    container_name: documize
    image: alpine:latest
    command:  /bin/sh -c "apk update && apk add wget && wget https://documize.s3-eu-west-1.amazonaws.com/downloads/documize-enterprise-linux-amd64 && chmod 777 ./documize-enterprise-linux-amd64 && ./documize-enterprise-linux-amd64"
    environment:
      DOCUMIZEPORT: 5001
      DOCUMIZEDB: host=db-name.ondigitalocean.com port=25000 dbname=documize user=documize password=P@SSw0rd sslmode=require
      DOCUMIZEDBTYPE: postgresql
      DOCUMIZESALT: hsk3Acndky8cdTNx3
      DOCUMIZELOCATION: selfhost
    restart: always
    networks:
      - web
    ports:
    - "5001:5001" 
```

In theory it should produce a smaller image with a more secure base.
